### PR TITLE
fix(sensor): change configuration and delta in adxl - PerformSelftest

### LINKED ISSUE #390: fix adxl345bPerformSelfTest
- [x] figure out correct values
- [x] document calculation

### PR DESCRIPTION
**Pull request by PandiasChild**

### CODE REVIEW

File: src/sensor/adxl345b/Adxl345b.c [hunk 1]
```diff
@@ -352,30 +352,40 @@ adxl345bErrorCode_t adxl345bPerformSelfTest(adxl345bSensorConfiguration_t sensor
...
+        adxl345bWriteConfigurationToSensor(sensor, ADXL345B_REGISTER_BW_RATE, ADXL345B_BW_RATE_100);
     if (errorCode != ADXL345B_NO_ERROR) {
         return errorCode;
     }
-    /* right adjusted, 16G range */
-    errorCode = adxl345bChangeMeasurementRange(sensor, ADXL345B_16G_RANGE);
+
+    /* disable selftest_bit, enable 16g full resolution  */
+    errorCode =
+        adxl345bWriteConfigurationToSensor(sensor, ADXL345B_REGISTER_DATA_FORMAT, 0b00001011);
```
Comment (DavidFederl) [inline src/sensor/adxl345b/Adxl345b.c:377]: use original adxl345bChangeMeasurementRange `adxl345bChangeMeasurementRange(...)` method and add function to `setSelfTest(...)` to enable force.

File: src/sensor/adxl345b/Adxl345b.c [hunk 2]
```diff
@@ -419,28 +429,28 @@ adxl345bErrorCode_t adxl345bPerformSelfTest(adxl345bSensorConfiguration_t sensor
...
     }
-    int avgSampleWithoutForceX = sumSamplesWithoutForceX / 100;
-    int avgSampleWithoutForceY = sumSamplesWithoutForceY / 100;
-    int avgSampleWithoutForceZ = sumSamplesWithoutForceZ / 100;
+    int avgSampleWithoutForceX = sumSamplesWithoutForceX / numberOfSamples;
+    int avgSampleWithoutForceY = sumSamplesWithoutForceY / numberOfSamples;
+    int avgSampleWithoutForceZ = sumSamplesWithoutForceZ / numberOfSamples;
 
-    /* enable self test force */
+    /* enable selftest_bit, while keeping 16g full resolution  */
```
Comment (DavidFederl) [inline src/sensor/adxl345b/Adxl345b.c:441]:
```suggestion
    /* set selftest_bit to enable force, while keeping 16g full resolution  */
```

**Review by DavidFederl — CHANGES_REQUESTED** [review]

**Review by glencoe — CHANGES_REQUESTED** [review]

File: src/sensor/adxl345b/Adxl345b.c [hunk 3]
```diff
@@ -244,328 +258,286 @@ adxl345bErrorCode_t adxl345bGetMultipleMeasurements(adxl345bSensorConfiguration_
...
+    while (counter < numberOfSamples) {
         uint8_t interrupt_source;
         errorCode = adxl345bInternalReadDataFromSensor(sensor, ADXL345B_REGISTER_INTERRUPT_SOURCE,
                                                        &interrupt_source, 1);
         if (errorCode != ADXL345B_NO_ERROR) {
             return errorCode;
         }
 
-        if (interrupt_source & 0b10000000) {
+        if ((interrupt_source & ADXL345B_BITMASK_DATA_READY) == ADXL345B_BITMASK_DATA_READY) {
```
Comment (DavidFederl) [inline src/sensor/adxl345b/Adxl345b.c:342]: Should be sufficient:
```suggestion
        if (interrupt_source & ADXL345B_BITMASK_DATA_READY) {
```

File: src/sensor/adxl345b/Adxl345b.c [hunk 4]
```diff
@@ -8,13 +8,26 @@
 #include "Time.h"
 #include "include/Adxl345bTypedefs.h"
 
+#include "math.h"
+
```
Comment (DavidFederl) [inline src/sensor/adxl345b/Adxl345b.c:12]: If you start splitting the headers, I would suggest to move the C standard header to the top.

**Review by DavidFederl — APPROVED** [review]
Addressed changes are optional, feel free to apply them, or not.

**Comment by PandiasChild** [comment]
@DavidFederl  @glencoe can we please merge this into main?
