### PR TITLE
fix(sensor): change Measurement Functions

### LINKED ISSUE #405: fix adxl measurement functions
there is a bug in adxl345bGetMeasurementsForNMilliseconds with the time library (wrap around)
besides this lukas requested some changes for the getMeasurementsForNMilliseconds:
- [x] take wrap around of time library into account 
- [x] extract some code into other static functions to make it more readable 
- [ ] make debug output on line 205 specific or remove
- [ ] change debug output on line 191 
- [ ]  figure out where i could use a buffer struct that contains buffer and its size and pass that per value to the functions (create simple macro to create and initialize one of these with a single line)
- [x] make bitmasks more expressive (maybe splitting into other functions)

- [ ] [change naming of static internal functions]

check in other functions:
- [ ] are there any analogue problems
- [x]  handle the size "6" in adxl - which occurs often (we receive Data in uint8_t each: X1, X2, Y1, Y2, Z1, Z2)

### PR DESCRIPTION
**Pull request by DavidFederl**
BREAKING-CHANGE:
- Measuring Functions now require RawData array which replaces uint8_t array and reduces many calculations
- GetMeasurementsForNMilliseconds changed to GetMeasurementsForNMicroseconds

closes #405

### CODE REVIEW

File: src/sensor/adxl345b/include/eai/sensor/Adxl345bTypedefs.h [hunk 1]
```diff
@@ -130,6 +129,22 @@ typedef struct adxl345bSensorConfiguration {
...
+    struct {
+        uint8_t xZero;
+        uint8_t xOne;
+        uint8_t yZero;
+        uint8_t yOne;
+        uint8_t zZero;
+        uint8_t zOne;
+    } DataRegisters;
+    uint8_t data[ADXL345B_SIZE_OF_RAWDATA];
+} adxl345bRawData_t;
```
Comment (glencoe) [inline src/sensor/adxl345b/include/eai/sensor/Adxl345bTypedefs.h]: not a big deal, but I would not recommend answering the sizeof question with an enum. There is the sizeof operator for this. Of course that requires the struct that you're using to not be anonymous.

File: test/unit/dummies/hal/i2c/include/I2cUnitTest.h [hunk 2]
```diff
@@ -1,15 +1,17 @@
...
-#include "eai/hal/I2cTypedefs.h"
-#include <stdint.h>
+#include "eai/hal/I2c.h"
 
 /* region VARIABLES */
 
 static const uint8_t byteZero = 0xBE;
 static const uint8_t byteOne = 0xEF;
 static const uint8_t byteTwo = 0x55;
 static const uint8_t byteThree = 0xA7;
```
Comment (glencoe) [inline test/unit/dummies/hal/i2c/include/I2cUnitTest.h]: What are these?

File: test/unit/dummies/hal/i2c/include/I2cUnitTest.h [hunk 3]
```diff
@@ -79,6 +81,16 @@ i2cErrorCode_t i2cUnittestReadCommandPassForAdxl345bInTriggerMode(uint8_t *readB
...
+i2cErrorCode_t i2cUnittestReadCommandPassForAdxl345bWithFullResON(uint8_t *readBuffer,
+                                                                  uint8_t sizeOfReadBuffer,
+                                                                  uint8_t slaveAddress,
+                                                                  i2c_inst_t *i2cHost);
+
+i2cErrorCode_t i2cUnittestReadCommandPassForAdxl345bWithFullResOFF(uint8_t *readBuffer,
+                                                                   uint8_t sizeOfReadBuffer,
+                                                                   uint8_t slaveAddress,
+                                                                   i2c_inst_t *i2cHost);
+
```
Comment (glencoe) [inline test/unit/dummies/hal/i2c/include/I2cUnitTest.h:91]: If this is specific only for the adxl345 i don't see why it should be in a general i2c dummy header. Same goes for the pac193 stuff below, tbh.

File: test/unit/UnitTestAdxl345b.c [hunk 4]
```diff
@@ -11,57 +12,69 @@
...
+static uint32_t checkIfDataIsZero(adxl345bRawData_t *samples, uint8_t expectetRawData) {
+    uint32_t counter = 0;
+    for (int i = 0; i < numberOfSamples; i++) {
+        for (int j = 0; j < ADXL345B_SIZE_OF_RAWDATA; j++) {
+            if (samples[i].data[j] == 0) {
+                counter++;
+            } else {
+                printf("expected: %b, ", expectetRawData);
+                printf("actual: %b \n", samples[i].data[j]);
+            }
```
Comment (glencoe) [inline test/unit/UnitTestAdxl345b.c]: Why would we have print statements in unit tests? Either we check smth., then that should be self-verifying, ie. assert, or this adds noise to a growing collection of tests.

File: test/unit/UnitTestAdxl345b.c [hunk 5]
```diff
@@ -76,619 +89,482 @@ void adxl345bReadSerialNumberReadCorrectValue(void) {
...
     /* change ReadCommands to generate expected raw data received from I2C*/
     i2cUnittestReadCommand = i2cUnittestReadCommandPassForAdxl345bInTriggerMode;
+    uint8_t expectedRawData = byteThree;
 
     adxl345bErrorCode_t errorCode =
-        adxl345bGetMultipleMeasurements(sensor, samples, sizeOfRequestedRawData);
+        adxl345bGetMultipleMeasurements(sensor, samples, numberOfSamples);
     if (errorCode != ADXL345B_NO_ERROR) {
-        TEST_FAIL_MESSAGE("If this ever occurs and no other test fails, please write test for it.");
+        TEST_FAIL();
```
Comment (glencoe) [inline test/unit/UnitTestAdxl345b.c]: maybe add a message here that tells why the test failed?

File: test/unit/UnitTestAdxl345b.c [hunk 6]
```diff
@@ -76,619 +89,482 @@ void adxl345bReadSerialNumberReadCorrectValue(void) {
...
-        TEST_MESSAGE("case: given buffer was too small for given milliseconds");
-        TEST_ASSERT_EACH_EQUAL_UINT8(expectedRawData, samples, sizeOfRequestedRawData);
-    } else {
-        TEST_FAIL_MESSAGE("adxl345bGetMeasurementsForNMilliseconds probably returns wrong "
-                          "sizeOfRequestedRawData (or else)");
+    adxl345bErrorCode_t errorCode =
+        adxl345bGetMeasurementsForNMicroseconds(sensor, microseconds, samples, numberOfSamples);
+    /* we expect a parameter error, because we use DUMMY-TIME-FACADE-LIB */
+    if (errorCode != ADXL345B_PARM_ERROR) {
+        TEST_FAIL();
```
Comment (glencoe) [inline test/unit/UnitTestAdxl345b.c:371]: see above

File: test/unit/UnitTestAdxl345b.c [hunk 7]
```diff
@@ -76,619 +89,482 @@ void adxl345bReadSerialNumberReadCorrectValue(void) {
...
+/* endregion adxl345bGetMeasurementsForNMicroseconds */
 
-    /*generate Array for Data*/
-    uint8_t wrongSize = 2;
-    uint32_t sizeOfRequestedRawData = numberOfSamples * sizeOfSingleRawData + wrongSize;
-    uint8_t samples[sizeOfRequestedRawData];
-    memset(samples, 0, sizeOfRequestedRawData);
+void adxl345bConvertDataXYZCorrectValueWithFullResON(void) {
+    /* test assumes that 2G Full Range is the used Range */
+    adxl345bErrorCode_t errorCode = adxl345bChangeMeasurementRange(sensor, ADXL345B_2G_RANGE);
```
Comment (glencoe) [inline test/unit/UnitTestAdxl345b.c]: I'd say the code is already pretty clear about the range, no need for the comment

File: test/unit/UnitTestAdxl345b.c [hunk 8]
```diff
@@ -76,619 +89,482 @@ void adxl345bReadSerialNumberReadCorrectValue(void) {
...
+        TEST_FAIL();
+    }
 
-    /* change ReadCommands to generate expected raw data received from I2C*/
-    i2cUnittestReadCommand = i2cUnittestReadCommandPassForAdxl345bInTriggerMode;
-    uint8_t expectedRawData = byteThree;
+    float expected_xAxis = 0, expected_yAxis = 0, expected_zAxis = 0;
+    float actual_xAxis = 0, actual_yAxis = 0, actual_zAxis = 0;
+    const uint8_t MSB_MASK = 0b00000011;
+    // const float SCALE_FACTOR_FOR_RANGE = 0.00391; //ten-bit
```
Comment (glencoe) [inline test/unit/UnitTestAdxl345b.c]: why is this commented out?

File: test/unit/UnitTestAdxl345b.c [hunk 9]
```diff
@@ -76,619 +89,482 @@ void adxl345bReadSerialNumberReadCorrectValue(void) {
...
+    const float SCALE_FACTOR_FOR_RANGE = 0.00377f;
+    /* only used lower 2 bits -> 2G Range consists of 10 Bit*/
+    uint8_t topByte = byteZero & MSB_MASK;
```
Comment (glencoe) [inline test/unit/UnitTestAdxl345b.c]: unclear where byte zero comes from here and what it's supposed to mean. I think this would greatly benefit from having the byteZero variable declared at file scope in this file here.

File: test/unit/UnitTestAdxl345b.c [hunk 10]
```diff
@@ -76,619 +89,482 @@ void adxl345bReadSerialNumberReadCorrectValue(void) {
...
+         * -> number-1 and Flip least 9 bits
+         * 2. convert to float value
+         * 3. multiply with (-1)
+         * 4. multiply with scale factor
+         */
+        uint16_t rawValue = ((uint16_t)(topByte & (MSB_MASK >> 1)) << 8) | (uint16_t)byteZero;
+        rawValue = (rawValue - 0x0001) ^ (((MSB_MASK >> 1) << 8) | 0x00FF);
+        float realValue = (-1) * (float)rawValue * SCALE_FACTOR_FOR_RANGE;
+        expected_xAxis = expected_yAxis = expected_zAxis = realValue;
+    }
```
Comment (glencoe) [inline test/unit/UnitTestAdxl345b.c]: why do we need to do all this conversion? In unit test i'd expect us to inject the value that will be read from the sensor and check if it is converted correctly. Hence we'd know the result in advance and could hard code it in human readable form.

File: test/unit/UnitTestAdxl345b.c [hunk 11]
```diff
@@ -76,619 +89,482 @@ void adxl345bReadSerialNumberReadCorrectValue(void) {
...
+    i2cUnittestReadCommand = i2cUnittestReadCommandPassForAdxl345bWithFullResON;
+    errorCode =
+        adxl345bConvertDataXYZ(sensor, &actual_xAxis, &actual_yAxis, &actual_zAxis, rawData);
+    if (errorCode != ADXL345B_NO_ERROR) {
+        TEST_FAIL();
     }
+
+    printf("%b \n", actual_xAxis);
+    printf("%b \n", actual_yAxis);
+    printf("%b \n", actual_zAxis);
```
Comment (glencoe) [inline test/unit/UnitTestAdxl345b.c]: please avoid prints in unit tests

File: test/unit/UnitTestAdxl345b.c [hunk 12]
```diff
@@ -76,619 +89,482 @@ void adxl345bReadSerialNumberReadCorrectValue(void) {
...
-/* endregion adxl345bGetMeasurementsForNMilliseconds */
 
-void adxl345bConvertDataXYZCorrectValue(void) {
-    /* test assumes that 2G Full Range is the used Range */
+void adxl345bConvertDataXYZCorrectValueWithFullResOFF(void) {
+    /* test assumes that 2G 10Bit Range is the used Range */
+    adxl345bErrorCode_t errorCode = adxl345bChangeMeasurementRange(sensor, ADXL345B_2G_RANGE);
+    if (errorCode != ADXL345B_NO_ERROR) {
+        printf("adxl345bChangeMeasurementRange failed; adxl345b_ERROR: %02X", errorCode);
+        TEST_FAIL();
```
Comment (glencoe) [inline test/unit/UnitTestAdxl345b.c]: move the string from print into the test fail macro call. Possible that it doesn't dispatch automatically and there is smth like `TEST_FAIL_MESSAGE`. I don't exactly remember that atm.

File: test/unit/UnitTestAdxl345b.c [hunk 13]
```diff
@@ -76,619 +89,482 @@ void adxl345bReadSerialNumberReadCorrectValue(void) {
...
 
     float expected_xAxis = 0, expected_yAxis = 0, expected_zAxis = 0;
     float actual_xAxis = 0, actual_yAxis = 0, actual_zAxis = 0;
     const uint8_t MSB_MASK = 0b00000011;
+    // const float SCALE_FACTOR_FOR_RANGE = 0.00391; //ten-bit
     const float SCALE_FACTOR_FOR_RANGE = 0.00377f;
     /* only used lower 2 bits -> 2G Range consists of 10 Bit*/
     uint8_t topByte = byteZero & MSB_MASK;
 
     /* set rawData */
```
Comment (glencoe) [inline test/unit/UnitTestAdxl345b.c]: haven't i seen this exact code above already?

File: test/unit/UnitTestAdxl345b.c [hunk 14]
```diff
@@ -710,9 +586,24 @@ void adxl345bConvertDataXYZCorrectValue(void) {
...
+    }
+    if (errorCode != ADXL345B_NO_ERROR) {
+        printf("adxl345bGetSingleMeasurement failed; adxl345b_ERROR: %02X", errorCode);
+        TEST_FAIL();
+    }
+    i2cUnittestReadCommand = i2cUnittestReadCommandPassForAdxl345bWithFullResOFF;
+    errorCode =
+        adxl345bConvertDataXYZ(sensor, &actual_xAxis, &actual_yAxis, &actual_zAxis, rawData);
+    if (errorCode != ADXL345B_NO_ERROR) {
+        TEST_FAIL();
```
Comment (glencoe) [inline test/unit/UnitTestAdxl345b.c]: The print statements.

The fact that we'd expect all these errors, worries me a little bit i have to admit.

File: test/unit/UnitTestAdxl345b.c [hunk 15]
```diff
@@ -746,41 +645,30 @@ int main(void) {
...
-    RUN_TEST(
-        adxl345bGetMeasurementsForNMillisecondsReadCorrectValuesInFifoModeWithCorrectSizedArray);
-    RUN_TEST(adxl345bGetMeasurementsForNMillisecondsReadCorrectValuesInFifoModeWithWrongSizedArray);
-    RUN_TEST(
-        adxl345bGetMeasurementsForNMillisecondsReadCorrectValuesInTriggerModeWithCorrectSizedArray);
-    RUN_TEST(
-        adxl345bGetMeasurementsForNMillisecondsReadCorrectValuesInTriggerModeWithWrongSizedArray);
-
-    RUN_TEST(adxl345bConvertDataXYZCorrectValue);
+    // GetMeasurementsForNmicroseconds
```
Comment (glencoe) [inline test/unit/UnitTestAdxl345b.c]: why do we need this comment?

**Review by glencoe — CHANGES_REQUESTED** [review]

File: src/sensor/adxl345b/include/eai/sensor/Adxl345bTypedefs.h (hunk 1 above)
Comment (PandiasChild) [reply src/sensor/adxl345b/include/eai/sensor/Adxl345bTypedefs.h]: thank you for the recommendation. i totally forgot the size of operator. I changed it.

File: test/unit/UnitTestAdxl345b.c (hunk 4 above)
Comment (PandiasChild) [reply test/unit/UnitTestAdxl345b.c]: i deleted it completely since i realized that the test i wrote it for were pointless

File: test/unit/dummies/hal/i2c/include/I2cUnitTest.h (hunk 2 above)
Comment (PandiasChild) [reply test/unit/dummies/hal/i2c/include/I2cUnitTest.h]: i changed it back to byteZero and byteOne but still don't know how to make it more transparent whats happening with the bytes. Unfortunately the i2c functions for the sensors are all in the i2c library. As you mention in the other comment.
Since I2C shows different behavior with each sensor we need this differentiation. 
I could put them each in a different header. maybe something like "i2cAdxlResponses"/"i2cPacResponses"? 
Or do you have something else in mind?

File: test/unit/dummies/hal/i2c/include/I2cUnitTest.h (hunk 3 above)
Comment (PandiasChild) [reply test/unit/dummies/hal/i2c/include/I2cUnitTest.h:91]: [see other comment](https://github.com/es-ude/elastic-ai.runtime.enV5/pull/436/files/98cc2e1f241eb2a005768c3298122e9b40904cf1#r2328626023)

File: test/unit/UnitTestAdxl345b.c (hunk 12 above)
Comment (PandiasChild) [reply test/unit/UnitTestAdxl345b.c]: unfortunately the macro does not allow printing the errorCode. It only allows "message" 

we could use this as a macro:
#define TEST_FAIL_MESSAGE_FORMAT(message, ...) \
    do { \
        char message_str[1024]; \
        sprintf(message_str, message, ##__VA_ARGS__); \
        TEST_FAIL_MESSAGE(message_str); \
    } while (false)
    
would you write this into common.h or leave it in the unit tests
